Fix lightgbm binding keyword argument bugs
allegroai/trains pull request #251
Opened 2020-11-18 08:25 UTC by noklam

Prevent error when user using keyword arguments instead of positional arguments

2020-11-18 12:29 UTC, JDennisJ requested changes

2020-11-18 12:29 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
How about sending the args to the original function too? Just `ret = original_fn(*args, **kwargs)`, and let's not parse the args at all.

With this parsing method, we will get an exception for using `pop` (and basically, we need to get only the `params`).

2020-11-18 12:29 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = kwargs['params']
For getting the `params`, we can use `params = args[0] if args else kwargs['params']` to support both ways

2020-11-18 14:19 UTC, noklam commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
Why would it get exception? if args is empty, it would not trigger the pop() at all. train_set is also a positional argument, so we need to have to deal with 3 condition
1. both positional
2. params positional and train_set is keyword
3. both keywords

2020-11-18 14:22 UTC, noklam commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
if args is an empty list  -> *args will become *None and will throw error instead?

2020-11-18 14:27 UTC, noklam commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = kwargs['params']
This can be used if pop() is not used, but I found using pop keep it cleaner and I can get rid of checking is arg is None or leng == 1 or len ==2

2020-11-18 15:00 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
`args` are `Tuple`, so `pop` raising an exception (for conditions 1 and 2).

What do you get running https://github.com/allegroai/trains/blob/master/examples/frameworks/lightgbm/train_with_lightbgm.py (condition 1)?

2020-11-18 15:01 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = kwargs['params']
https://github.com/allegroai/trains/pull/251/files#r526154397, we can not use `pop`...

2020-11-18 15:17 UTC, noklam commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
@JDennisJ How about the fix now. should work for all 3 cases.

2020-11-18 15:49 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        ret = original_fn(**kwargs)
For those 3 cases - yes, but with this solution, you are guessing the user will send a max of 2 parameters for `args` (or forcing the user to do so).

If we will take the example above (https://github.com/allegroai/trains/blob/master/examples/frameworks/lightgbm/train_with_lightbgm.py), and replace [this](https://github.com/allegroai/trains/blob/master/examples/frameworks/lightgbm/train_with_lightbgm.py#L50) with

```
gbm = lgb.train(
    params,
    lgb_train,
    20,
    valid_sets=lgb_eval,
    early_stopping_rounds=5
)
```
it should still work, but we will get an exception with the changes.

But, if we will send `ret = original_fn(*args, **kwargs)`, we are just a pipe in the way, so if the user used `lgb.train` in any valid way, we will pass it to the original function and won't fail.

Other than that, we are parsing `train_set` without any reason.

2020-11-18 17:43 UTC, noklam reviewed
@JDennisJ I modified the PR. Yes you are right, now I don't even know why I thought I had to parse the argument in the first place, it seems obvious.

2020-11-22 14:21 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = args[0] if args else kwargs['params']
`kwargs['params']` -> `kwargs.get('params', {})` just to be on the safe side

2020-11-22 14:21 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = args[0] if args else kwargs['params']
and need to add [here](https://github.com/allegroai/trains/pull/251/files#diff-7419bbefd8f631446dbf82d2e6bae476070d71d5735a27791aeca2b80218bfb4L129) `if params` just for the `connect` part

2020-11-24 11:27 UTC, merged

2020-11-25 01:15 UTC, noklam commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = args[0] if args else kwargs['params']
The PR is merged already, can you make these changes directly, or I should create another PR?

2020-11-25 08:57 UTC, JDennisJ commented on trains/binding/frameworks/lightgbm_bind.py
> +        params = args[0] if args else kwargs['params']
@noklam Sure, I will make those.

Thanks for your contribution  :)